name: "Bug"
description: 问题报告.
title: "[BUG] "
labels: [bug]
body:

  - type: checkboxes
    id: check
    attributes:
      label: 须知
      description: |
        Please confirm that all required options have been followed, otherwise it cannot be ruled out that the issue will be closed directly
        请确认已经遵守所有必选项，否则不排除将直接关闭 Issue
      options:
        - label: I am using the latest version of akashaProxy/我使用的是最新版akashaProxy.
          required: true

        - label: I confirm that this is not a core issue with mihomo/我确认这不是mihomo核心的问题.
          required: true

        - label: I confirm that this is not a problem caused by a configuration file error/我确认这不是配置文件错误导致的问题.
          required: true

          
  - type: dropdown
    id: browsers
    attributes:
      label: What is the root manager you are using/你的使用的root管理器是？
      multiple: false
      options:
        - Magisk release
        - KernelSU
        - Magisk Alpha
        - apatch
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behaviour/预期行为
      placeholder: Tell us what should happen/正常情况下应该发生什么
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual behaviour / 实际行为
      placeholder: Tell us what happens instead / 实际上发生了什么
    validations:
      required: true

  - type: textarea
    attributes:
      label: "Steps to reproduce/复现步骤"
      placeholder: .......
    validations:
      required: true


  - type: textarea
    id: log
    attributes:
      label: "module log/模块日志"
      description: 
      placeholder: .......
    validations:
      required: true

