name: ci

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set ENV
      run: |
        sudo timedatectl set-timezone "Asia/Shanghai"
        [ ! -f module/bin ] && mkdir module/bin
        text="${{ github.event.head_commit.message }}"
        echo "buildSha=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        echo "commit=$(echo $text | sed 's/\([][\\`.*^$\/+?{}()=!|:-]\)/\\\1/g')" >> $GITHUB_ENV

    - uses: pnpm/action-setup@v4
      name: Setup pnpm
      with:
        version: 10
        run_install: false

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.2'

    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1
      id: setup-ndk
      with:
        ndk-version: r26b
        add-to-path: true

    - name: Install zip
      uses: montudor/action-zip@v1

    - name: Install UPX
      uses: crazy-max/ghaction-upx@v3
      with:
        install-only: true

    - name: Pack Module
      run: |
        make CC=${ANDROID_NDK_HOME}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android33-clang

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: akashaProxy.zip
        path: akashaProxy.zip

    - name: Find ZIP
      run: |
          cp -Rf akashaProxy.zip akashaProxy-${{ env.buildSha }}.zip
          echo "ZIP_FILE=$(find . -name 'akashaProxy-${{ env.buildSha }}.zip')" >> $GITHUB_ENV
  
    - name: Post to Telegram Channel
      if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
      env:
        CHANNEL_ID: ${{ secrets.TELEGRAM_TO }}
        BOT_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        FILE: ${{ env.ZIP_FILE }}
        COMMIT_MESSAGE: |+
          **New push to github\!**

          `${{ env.commit }}`
              
          by ${{ github.event.head_commit.author.name }}
          For more architecture see [action](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
          See commit detail [here](${{ github.event.head_commit.url }})
      run: |
        ESCAPED=$(python3 -c 'import json,os,urllib.parse; print(urllib.parse.quote(json.dumps(os.environ["COMMIT_MESSAGE"])))')
        curl -v "https://api.telegram.org/bot${BOT_TOKEN}/sendMediaGroup?chat_id=${CHANNEL_ID}&media=%5B%7B%22type%22:%22document%22,%20%22media%22:%22attach://release%22,%22parse_mode%22:%22MarkdownV2%22,%22caption%22:${ESCAPED}%7D%5D" -F release="@${FILE}"
            
    - name: Upload release
      uses: softprops/action-gh-release@v1
      with:
          tag_name: ${{ github.ref_name }}
          files: akashaProxy.zip
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true
          prerelease: true